### ISSUE TITLE
Default staging configuration not honored

### ISSUE THREAD

**Issue by aweiteka** [projectatomic/atomic#644]
With a default sigstore-staging defined and a separate https sigstore "read" value for a specific registry, skopeo returns "Writing to https is not supported. Use a supported scheme ['file'] instead." I would expect the default staging value to be used in this case.

atomic v1.12.3
skopeo version 0.1.14-dev commit: d8303916d52272e08d92163bba18e30c50ee24d7

```
$ sudo atomic push --sign-by aweiteka@gmail.com docker.io/aweiteka/hello-openshift:signed -u aweiteka
Registry Password:
Writing to https is not supported. Use a supported scheme ['file'] instead.

$ cat /etc/containers/registries.d/default.yaml
default-docker:
#  sigstore: file:///var/lib/atomic/sigstore
  sigstore-staging: file:///var/lib/atomic/sigstore

$ cat /etc/containers/registries.d/docker.io-aweiteka.yaml
docker:
  docker.io/aweiteka:
    sigstore: https://s3.amazonaws.com/aweiteka-sigstore
```

**Comment by baude** [comment]
@aweiteka that error comes from atomic.  I agree this should work, Ill check into it

**Comment by aweiteka** [comment]
@mtrmac anything in skopeo blocking this?

**Comment by baude** [comment]
@mtrmac more importantly, considering Aaron's use case, how are you handling this? I will follow suit in atomic.

**Comment by mtrmac** [comment]
https://github.com/containers/image/blob/master/docs/registries.d.md explicitly says 

>  only the configuration for the most-precisely matching scope is used; configuration using more general scopes is ignored. For example, if any configuration exists for docker.io/library/busybox, the configuration for docker.io is ignored (even if some element of the configuration is defined for docker.io and not for docker.io/library/busybox).

I think this makes sense, it makes the code simpler, the semantics simpler (there are interactions between the per-repo options, and there will likely be more in the future; so looking up for options independently and then combining them could result in unexpected results), and especially when we can have the configuration spread over various files, this semantics is the only thing keeping related configuration in a single place.

---

WRT the example above, _should_ this work? Why should completely different public locations use a single sigstore? Then somebody would have to write an extra tool to disentangle them and to publish the staged subdirectories into separate locations; it seems far simpler to have separate `sigstore-staging` subdirectories for every public URL, and just copy all files from each such directory into the respective webroot.

Also, wouldn’t the common case be that a user adds a `sigstore: http…` for a third party repo? In that case we really want local attempts to sign to fail.

(It is perfectly fine to do
```yaml
default-docker:
#  sigstore: file:///var/lib/atomic/sigstore
  sigstore-staging: file:///var/lib/atomic/sigstore

$ cat /etc/containers/registries.d/docker.io-aweiteka.yaml
docker:
  docker.io/aweiteka:
    sigstore: https://s3.amazonaws.com/aweiteka-sigstore
    sigstore-staging: file:///var/lib/atomic/sigstore-amazon
```
or, to get the semantics you expected, to use the same `file:///` path for both locations.)
